version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_ENV=development
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: redis
    ports:
      - "6379:6379"